#!/usr/bin/env python3
"""WorkerCoordinator-bound synthetic conversation-evidence custody proof."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from conversation_evidence_ingestion import (
    build_ingestion_package,
    canonical_json,
    custody_ingestion,
    digest_bytes,
    persist_ingestion_package,
)

ROOT = Path.cwd().resolve()
RECEIPT_ROOT = (ROOT / "receipts" / "conversation-evidence-ingestion").resolve()
TASK_ID = "CONVERSATION-EVIDENCE-INGESTION-CUSTODY-001"
CAPABILITY = "conversation_evidence_synthetic_ingestion_custody"


def _safe(value: object) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "-", str(value or "")).strip("-") or "unknown"


def _synthetic_source(record_id: str) -> tuple[dict, dict[str, bytes]]:
    attachments = {"payment-receipt.txt": b"SYNTHETIC PAYMENT EVIDENCE ONLY\n"}
    source = {
        "record_id": record_id,
        "capture_method": "synthetic_workercoordinator_fixture",
        "source_platform": "stegverse.synthetic",
        "source_locator_or_export_identity": "synthetic://conversation-evidence-ingestion/runtime-proof",
        "captured_at": "2026-09-19T20:00:00Z",
        "conversation_start": "2026-09-19T19:58:00Z",
        "conversation_end": "2026-09-19T19:59:00Z",
        "participant_assertions": [
            {"participant_id": "synthetic-provider", "role": "service_provider"},
            {"participant_id": "synthetic-customer", "role": "customer"},
        ],
        "message_sequence": [
            {
                "ordinal": 1,
                "source_message_id": "synthetic-m1",
                "speaker_assertion": "synthetic-provider",
                "timestamp_assertion": "2026-09-19T19:58:00Z",
                "timestamp_precision": "second",
                "exact_content": "Synthetic service representation for custody-path validation only.",
                "attachment_ids": [],
            },
            {
                "ordinal": 2,
                "source_message_id": "synthetic-m2",
                "speaker_assertion": "synthetic-customer",
                "timestamp_assertion": "2026-09-19T19:59:00Z",
                "timestamp_precision": "second",
                "exact_content": "Synthetic payment evidence attached for custody-path validation only.",
                "attachment_ids": ["payment-receipt.txt"],
            },
        ],
        "authenticity": {
            "state": "SOURCE_EXPORT_VERIFIED",
            "verified_claims": ["fixture generated by admitted synthetic runtime worker"],
            "evidence_refs": [],
        },
        "transaction_binding": {
            "service_representation": "synthetic-m1",
            "payment_evidence": "payment-receipt.txt",
            "finding_state": "NOT_EVALUATED",
        },
    }
    return source, attachments


def _persist_idempotent(package: dict, attachments: dict[str, bytes]) -> Path:
    record_root = RECEIPT_ROOT / package["record_id"]
    if not record_root.exists():
        return persist_ingestion_package(package, attachments, RECEIPT_ROOT)
    existing = json.loads((record_root / "package.json").read_text(encoding="utf-8"))
    if canonical_json(existing) != canonical_json(package):
        raise RuntimeError("existing synthetic package differs from current package")
    for attachment_id, raw in attachments.items():
        path = record_root / "attachments" / attachment_id
        if not path.is_file() or digest_bytes(path.read_bytes()) != digest_bytes(raw):
            raise RuntimeError("existing synthetic attachment differs from current attachment")
    return record_root


def main() -> int:
    try:
        invocation = json.load(sys.stdin)
    except Exception as exc:
        print(f"invalid invocation: {exc}", file=sys.stderr)
        return 2
    if invocation.get("schema") != "stegverse.worker-invocation/v0.1":
        print("unsupported invocation schema", file=sys.stderr)
        return 3

    task = invocation.get("task") or {}
    handoff = invocation.get("handoff") or {}
    if task.get("task_id") != TASK_ID:
        print("invocation outside admitted task", file=sys.stderr)
        return 4
    execution = handoff.get("execution") or {}
    required = set(execution.get("required_capabilities") or [])
    allowed = set(execution.get("allowed_paths") or [])
    if CAPABILITY not in required or "receipts/conversation-evidence-ingestion/**" not in allowed:
        print("synthetic ingestion capability/path not admitted", file=sys.stderr)
        return 5

    claim_id = task.get("claim_id")
    timing = task.get("heartbeat_timing") or {}
    fence = timing.get("fencing_token")
    if not claim_id or not isinstance(fence, int):
        print("fresh WorkerCoordinator claim/fence required", file=sys.stderr)
        return 6
    predecessor = task.get("claim_fence_master_records_transition")
    predecessor_complete = (
        isinstance(predecessor, dict)
        and predecessor.get("transition_id") == "WORKERCOORDINATOR_CLAIM_FENCE_BOUND"
        and predecessor.get("state") == "RECORDED"
        and predecessor.get("reconstruction_status") == "PASS"
        and predecessor.get("required_evidence_validation_status") == "PASS"
        and isinstance(predecessor.get("receipt_sha256"), str)
        and predecessor.get("receipt_sha256") == predecessor.get("reconstructed_receipt_sha256")
    )
    if not predecessor_complete:
        print("closed WorkerCoordinator claim/fence Master Records predecessor required", file=sys.stderr)
        return 7

    record_id = f"SYNTH-CONVERSATION-EVIDENCE-{_safe(claim_id)}-F{fence}"
    source, attachments = _synthetic_source(record_id)
    package = build_ingestion_package(source, attachments)
    record_root = _persist_idempotent(package, attachments)
    custody = custody_ingestion(
        package,
        predecessor_receipt_sha256=str(predecessor["receipt_sha256"]),
    )

    if custody.get("state") != "RECORDED":
        response = {
            "schema": "stegverse.worker-response/v0.1",
            "state": "BLOCKED",
            "transition_id": "CONVERSATION_EVIDENCE_INGESTED",
            "transition_sequence": 1,
            "expected_next_transition": "CONVERSATION_EVIDENCE_INGESTED",
            "checkpoint_ref": str(record_root.relative_to(ROOT) / "package.json"),
            "evidence_refs": [str(record_root.relative_to(ROOT) / "package.json")],
            "reason": custody.get("reason"),
            "master_records": custody.get("master_records"),
            "authority_effect": "NONE_FAIL_CLOSED",
        }
        json.dump(response, sys.stdout, sort_keys=True)
        sys.stdout.write("\n")
        return 0

    mr = custody["master_records"]
    response = {
        "schema": "stegverse.worker-response/v0.1",
        "state": "COMPLETED",
        "transition_id": "CONVERSATION_EVIDENCE_INGESTED",
        "transition_sequence": 1,
        "expected_next_transition": None,
        "checkpoint_ref": str(record_root.relative_to(ROOT) / "package.json"),
        "evidence_refs": [str(record_root.relative_to(ROOT) / "package.json")],
        "master_records": {
            "state": mr.get("state"),
            "reconstruction_status": mr.get("reconstruction_status"),
            "required_evidence_validation_status": mr.get("required_evidence_validation_status"),
            "receipt_sha256": mr.get("receipt_sha256"),
            "reconstructed_receipt_sha256": mr.get("reconstructed_receipt_sha256"),
        },
        "synthetic_fixture_only": True,
        "publication_performed": False,
        "adjudication_performed": False,
        "authority_effect": "NONE_CUSTODY_RECONSTRUCTION_ONLY",
        "cost_observation": {
            "hb_transition_count": 1,
            "compute_units": 1,
            "external_cost_usd": 0,
            "task_class": "conversation_evidence_synthetic_ingestion",
        },
    }
    json.dump(response, sys.stdout, sort_keys=True)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
